site_name: CMV
site_description: CMV - The Configurable Map Viewer. Make it your own!
site_url: http://cmv.io/
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/cmv/cmv-app

docs_dir: ./docs
strict: true
theme: yeti
#theme: spacelab
#theme: readthedocs

pages:
- Getting Started:
  - Introduction: index.md
  - Installation: installation.md
  - Configure: configure/index.md
  - Support: support.md
  - Development Environment: develop.md
- Configure:
  - Introduction: configure/index.md
  - viewer.js: configure/viewer.md
  - basemaps.js: configure/basemaps.md
  - identify.js: configure/identify.md
- Viewer.js:
  - header: configure/header.md
  - MapOptions: configure/mapOptions.md
  - Operational Layers: configure/operationalLayers.md
  - Panes: configure/panes.md
  - Titles: configure/titles.md
  - Widgets: configure/widgets.md
- Widgets:
  - Introduction: widgets/index.md
  - BaseMaps: widgets/Basemaps.md
  - Bookmarks: widgets/Bookmarks.md
  - Directions: widgets/Directions.md
  - Draw: widgets/Draw.md
  - Editor: widgets/Editor.md
  - Find: widgets/Find.md
  - Geocoder: widgets/Geocoder.md
  - Growler: widgets/Growler.md
  - Help: widgets/Help.md
  - Home Button: widgets/HomeButton.md
  - Identify: widgets/Identify.md
  - Layer Control: widgets/LayerControl.md
  - Legend: widgets/Legend.md
  - Locate Button: widgets/LocateButton.md
  - Map Info: widgets/MapInfo.md
  - Measurement: widgets/Measurement.md
  - Overview Map: widgets/OverviewMap.md
  - Print: widgets/Print.md
  - Scalebar: widgets/Scalebar.md
  - StreetView: widgets/StreetView.md
- Contribute:
  - Introduction: contribute/index.md
  - Building Custom Widgets: contribute/BuildingCustomWidgets.md
  - Submitting a Pull Request: contribute/ContributingOnGitHub.md
  - Committing Changes to CMV: contribute/Committers.md
- About:
  - License: about/license.md
  - Change Log: about/changelog.md
  - The CMV Team: about/team.md
